version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      # specify the version you desire here
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:12.13.0
      - image: circleci/redis:6.0.6-alpine

    working_directory: ~/todo-typescript

    steps:
      - checkout
      # Download and cache dependencies
      # khôi phục lại folder chứa package (v1-dependencies) dựa vào file (package-lock.json)
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      # lưu lại cache folder theo key nếu như (package-lock.json) có sự thay đổi
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run: npm run test

  # deploy_development:
  #   machine:
  #     enabled: true
  #   steps:
  #     - add_ssh_keys:
  #         fingerprints:
  #           - "76:8d:4d:4c:2c:db:3f:0d:a6:6e:5a:42:f4:dc:c5:23"
  #     - run: 
  #         name: pull code and start api_services
  #         command: ssh -oStrictHostKeyChecking=no root@42.112.27.32 -p 22287 "cd /home/enetviet_data_synchronization; git pull origin master; npm run build-npm; npm run start-pro"

# workflows:
#   my-flow:
#       jobs:
#         - build-test
#         - deploy_development:
#             requires:
#               - build-test
#             filters:
#               branches:
#                 only:
#                   - master
